#!/usr/bin/env bash
# installs nginx on the server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo nginx -t

sudo service nginx restart


