#!/usr/bin/env bash
# installs nginx on the server

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo service nginx start
sudo ufw allow 'Nginx HTTP'


