#!/usr/bin/env bash
# installs, configures, and starts the load balancer
sudo apt-get update
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.8
sudo apt-get install -y haproxy
echo "
frontend web-front
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    balance roundrobin
    mode http
    server 299081-web-01 54.160.106.104:80 check
    server 299081-web-02 54.146.74.156:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy start
