#!/usr/bin/env bash
# A  Bash script that displays all active IPv4 IPs on the machine it’s executed on

ifconfig | grep -Eo "inet ([0-9]{1,3}\.)([0-9]{1,3}\.)([0-9]{1,3}\.)([0-9]{1,3}\.)" | cut -c 6-
