#!/usr/bin/env bash
# a script that configures nginx to be running as nginx user and listens on port 8080
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill -1 apache2
chmod 644 /etc/nginx/nginx.conf | sudo -u nginx service nginx restart
